target = args[0];
limit = args[1];
secLevel = args[2];
threads = args[3];

while (true) {
    //if (getServerSecurityLevel(target) - getServerBaseSecurityLevel(target) > ps(target)[0].threads * 0.05) {
    if (getServerSecurityLevel(target) - secLevel > threads * 0.05) {
        weaken(target);
    } else if (getServerMoneyAvailable(target) > limit || getServerMoneyAvailable("home") < getServerMoneyAvailable(target) / 10) {
        hack(target);
    }
    else{
        grow(target);
    }
}