clear(1);
//run node-finder that saves list of nodes as text file
run("node-finder.script");
//run breaker that separates nodes into hacked and not-hacked
run("node-breaker.script");
//run node-manager that keeps track of hacked nodes
run("node-manager.script");
//run serverBuyer that waits and buys new servers when appropriate
//run hacknet-manager that buys/upgrades hacknet nodes
//run stock trader